# Generated by Django 3.2.20 on 2023-08-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangovideoplatform', '0002_auto_20230816_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoTag',
        ),
        migrations.AddField(
            model_name='tag',
            name='video',
            field=models.ManyToManyField(to='djangovideoplatform.Video'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovideoplatform.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovideoplatform.video'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovideoplatform.user'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovideoplatform.video'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_id', to='djangovideoplatform.user'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovideoplatform.user'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangovideoplatform.user'),
        ),
    ]
