# Generated by Django 3.2.20 on 2023-08-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangovideoplatform', '0003_auto_20230816_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='user_id',
            new_name='user',
        ),
    ]
